[package]
name = "native-tls"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "0.1.4"

[target.'cfg(target_os = "windows")'.dependencies]
schannel = { git = "https://github.com/inejge/schannel-rs", branch = "impl-send" }

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies]
openssl = "0.7.11"
openssl-verify = "0.1"

[replace]
"winapi:0.2.7" = { git = "https://github.com/sfackler/winapi-rs" }
